name: elderly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  provider: ^6.1.2
  flutter_tts: ^4.2.2
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.1.4
  intl: ^0.20.2
  health: ^12.0.1
  firebase_core: ^3.3.0
  fl_chart: ^0.70.2
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  pedometer: ^4.0.2
  permission_handler: ^11.4.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  geocoding: ^3.0.0
  sensors_plus: ^6.1.1
  uuid: ^4.5.1
  firebase_database: ^11.3.4
  http: ^1.3.0
  animated_text_kit: ^4.2.3
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  assets:
    - .env
  uses-material-design: true
