// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDhfCiXGRuSSC-dMbYsqA5_qZO_RfeRI',
    appId: '1:270804337150:web:1006a15effcd35744500af',
    messagingSenderId: '270804337150',
    projectId: 'elderly-95825',
    authDomain: 'elderly-95825.firebaseapp.com',
    databaseURL: 'https://elderly-95825-default-rtdb.firebaseio.com',
    storageBucket: 'elderly-95825.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt71hOi54NEUJkzFN1s1_gkLVGSB9S5HQ',
    appId: '1:270804337150:android:9828291c1b300d044500af',
    messagingSenderId: '270804337150',
    projectId: 'elderly-95825',
    databaseURL: 'https://elderly-95825-default-rtdb.firebaseio.com',
    storageBucket: 'elderly-95825.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjDhfCiXGRuSSC-dMbYsqA5_qZO_RfeRI',
    appId: '1:270804337150:web:27674e75e424d00f4500af',
    messagingSenderId: '270804337150',
    projectId: 'elderly-95825',
    authDomain: 'elderly-95825.firebaseapp.com',
    databaseURL: 'https://elderly-95825-default-rtdb.firebaseio.com',
    storageBucket: 'elderly-95825.firebasestorage.app',
  );

}